/**
 * Weekly Plans Schema
 * Stores personalized weekly plans generated by AI agents
 */

import { pgTable, text, timestamp, uuid, jsonb, date } from 'drizzle-orm/pg-core'
import { users } from './users'
import { analyses } from './analyses'

export const weeklyPlans = pgTable('weekly_plans', {
  id: uuid('id').defaultRandom().primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  analysisId: uuid('analysis_id')
    .notNull()
    .references(() => analyses.id, { onDelete: 'cascade' }),
  weekStartDate: date('week_start_date').notNull(),

  // Supplementation strategy
  supplementationStrategy: jsonb('supplementation_strategy').notNull().$type<{
    overview: string
    supplements: Array<{
      name: string
      dosage: string
      timing: string
      purpose: string
      duration?: string
    }>
    hormonalSupport?: Array<{
      hormone: string
      strategy: string
      monitoring: string
    }>
    nextExamRecommendations?: string[]
  }>(),

  // Shopping list
  shoppingList: jsonb('shopping_list').notNull().$type<{
    overview: string
    categories: Array<{
      category: string
      items: Array<{
        item: string
        quantity?: string
        notes?: string
        priority?: 'high' | 'medium' | 'low'
      }>
    }>
    estimatedCost?: string
    tips?: string[]
  }>(),

  // Meal plan
  mealPlan: jsonb('meal_plan').notNull().$type<{
    overview: string
    dailyCalories?: string
    macros?: {
      protein?: string
      carbs?: string
      fats?: string
    }
    meals: Array<{
      day: string
      breakfast: {
        name: string
        ingredients: string[]
        calories?: string
        prepTime?: string
      }
      lunch: {
        name: string
        ingredients: string[]
        calories?: string
        prepTime?: string
      }
      dinner: {
        name: string
        ingredients: string[]
        calories?: string
        prepTime?: string
      }
      snacks?: Array<{
        name: string
        timing: string
        calories?: string
      }>
    }>
    mealPrepTips?: string[]
  }>(),

  // Workout plan
  workoutPlan: jsonb('workout_plan').notNull().$type<{
    overview: string
    weeklyGoal?: string
    workouts: Array<{
      day: string
      type: string
      duration: string
      intensity?: 'low' | 'medium' | 'high'
      exercises: Array<{
        name: string
        sets?: string
        reps?: string
        duration?: string
        notes?: string
      }>
      warmup?: string
      cooldown?: string
    }>
    restDays?: string[]
    progressionTips?: string[]
  }>(),

  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})

export type WeeklyPlan = typeof weeklyPlans.$inferSelect
export type NewWeeklyPlan = typeof weeklyPlans.$inferInsert
